### ISSUE TITLE
This module already exists

### ISSUE THREAD

**Issue by eserte** [davorg/template-plugin-lingua-en-inflexion#1]
There is already a module Template::Plugin::Lingua::EN::Inflexion on CPAN, see https://metacpan.org/release/HOUSTON/Template-Plugin-Lingua-EN-Inflexion-0.01
Consequently https://metacpan.org/release/DAVECROSS/Template-Plugin-Lingua-EN-Inflexion-0.0.1 is marked as "unauthorized".

Additionally, the distribution is lacking a Makefile.PL and cannot be built.

**Comment by davorg** [comment]
Yes, I realised that soon after I uploaded it - PAUSE sent me an email saying that the upload failed. But I didn't realise it had still been indexed. I've marked my unauthorised version to be deleted as soon as possible (which will be on Tuesday, 24 March).

Thanks for pointing it out.
